# ---- Build stage ----
FROM golang:1.22-alpine AS builder

WORKDIR /app

# docs/ is generated by the CI (swag init) before this build runs
# Copying go.mod+go.sum first maximises Docker layer cache
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o api .

# ---- Runtime stage ----
FROM alpine:3.19

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app
COPY --from=builder /app/api .

EXPOSE 8080
USER nobody

CMD ["./api"]
